monolog:
    channels:
        - deprecation
        - security

    handlers:
        main:
            type: fingers_crossed
            handler: nested
            buffer_size: 50
            excluded_http_codes: [404]

        nested:
            type: stream
            path: php://stderr
            level: debug

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: debug
            channels: ["security"]

        deprecation:
            type: stream
            path: php://stderr
            channels: [deprecation]

        mailer:
            type: stream
            path: php://stderr
            level: debug
            channels: ["mailer"]
