monolog:
    channels:
        - deprecation
        - security

    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]  # Cette option est valide ici
            buffer_size: 50

        nested:
            type: stream
            path: php://stderr
            level: debug

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: debug
            channels: ["security"]

        deprecation:
            type: stream
            path: php://stderr
            channels: [deprecation]
