security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: login_check
                default_target_path: /profile  # La page à laquelle rediriger après connexion

            logout:
                path: app_logout
                target: app_home

            stateless: false

    password_hashers:
        # On configure le hasher pour l'entité User
        App\Entity\User:
            algorithm: auto  # Symfony choisit automatiquement le meilleur algorithme (bcrypt/argon2i, etc.)


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # L'authentification se fait via l'email

    access_control:
        - { path: ^/admin/habitats/new, roles: [ROLE_ADMIN, ROLE_VETERINAIRE] }
        - { path: ^/admin/habitats/\d+/edit, roles: [ROLE_ADMIN, ROLE_VETERINAIRE] }
        - { path: ^/admin/animal/\d+/edit, roles: [ROLE_ADMIN, ROLE_VETERINAIRE] }
        - { path: ^/admin/animal/new, roles: [ROLE_ADMIN, ROLE_VETERINAIRE] }
