vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        animal_images:
            uri_prefix: /images/animals
            upload_destination: '%kernel.project_dir%/public/images/animals'
            namer:
                service: vich_uploader.namer_uniqid
