<?php

namespace ContainerLv6ty30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A20ZbmTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A20ZbmT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A20ZbmT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitat' => ['privates', '.errored..service_locator.A20ZbmT.App\\Entity\\Habitat', NULL, 'Cannot autowire service ".service_locator.A20ZbmT": it needs an instance of "App\\Entity\\Habitat" but this type has been excluded in "config/services.yaml".'],
            'habitatService' => ['privates', 'App\\Service\\HabitatService', 'getHabitatServiceService', true],
        ], [
            'habitat' => 'App\\Entity\\Habitat',
            'habitatService' => 'App\\Service\\HabitatService',
        ]);
    }
}
