<?php

namespace ContainerREUeL7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XPK4c2x.App\Controller\AnimalController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XPK4c2x.App\\Controller\\AnimalController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'animalService' => ['privates', 'App\\Service\\AnimalService', 'getAnimalServiceService', true],
        ], [
            'entityManager' => '?',
            'animalService' => 'App\\Service\\AnimalService',
        ]))->withContext('App\\Controller\\AnimalController::new()', $container);
    }
}
