<?php

namespace ContainerREUeL7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteRenduControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KoDioFC.App\Controller\CompteRenduController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KoDioFC.App\\Controller\\CompteRenduController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compteRendu' => ['privates', '.errored..service_locator.KoDioFC.App\\Entity\\CompteRendu', NULL, 'Cannot autowire service ".service_locator.KoDioFC": it needs an instance of "App\\Entity\\CompteRendu" but this type has been excluded in "config/services.yaml".'],
            'compteRenduService' => ['privates', 'App\\Service\\CompteRenduService', 'getCompteRenduServiceService', true],
        ], [
            'compteRendu' => 'App\\Entity\\CompteRendu',
            'compteRenduService' => 'App\\Service\\CompteRenduService',
        ]))->withContext('App\\Controller\\CompteRenduController::edit()', $container);
    }
}
