<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCjVYpyk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCjVYpyk/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCjVYpyk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCjVYpyk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCjVYpyk\App_KernelProdContainer([
    'container.build_hash' => 'CjVYpyk',
    'container.build_id' => 'bc9a7af4',
    'container.build_time' => 1733501200,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCjVYpyk');
