<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT8focgd\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT8focgd/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerT8focgd.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerT8focgd\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerT8focgd\App_KernelProdContainer([
    'container.build_hash' => 'T8focgd',
    'container.build_id' => '36b26dbc',
    'container.build_time' => 1733667954,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT8focgd');
