<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_sweetalert2_dist_sweetalert2_all_js-node_modules_core-js_modules_es_arra-0950c8.js',
                '/build/vendors-node_modules_swiper_modules_navigation_css-node_modules_swiper_modules_pagination_css-e0a7f9.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_swiper_modules_navigation_css-node_modules_swiper_modules_pagination_css-e0a7f9.css',
                '/build/app.css',
            ],
        ],
        'delete' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_sweetalert2_dist_sweetalert2_all_js-node_modules_core-js_modules_es_arra-0950c8.js',
                '/build/delete.js',
            ],
        ],
        'styles' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/styles.css',
            ],
        ],
    ],
],

]];
