<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Animal extends \App\Entity\Animal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'alimentation' => [parent::class, 'alimentation', null],
        "\0".parent::class."\0".'etatDeSante' => [parent::class, 'etatDeSante', null],
        "\0".parent::class."\0".'habitat' => [parent::class, 'habitat', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'race' => [parent::class, 'race', null],
        "\0".parent::class."\0".'visites' => [parent::class, 'visites', null],
        'alimentation' => [parent::class, 'alimentation', null],
        'etatDeSante' => [parent::class, 'etatDeSante', null],
        'habitat' => [parent::class, 'habitat', null],
        'id' => [parent::class, 'id', null],
        'images' => [parent::class, 'images', null],
        'nom' => [parent::class, 'nom', null],
        'race' => [parent::class, 'race', null],
        'visites' => [parent::class, 'visites', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
