parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    services_uploads_directory: '%kernel.project_dir%/public/uploads/services'
    habitats_uploads_directory: '%kernel.project_dir%/public/uploads/habitats'
    animals_uploads_directory: '%kernel.project_dir%/public/uploads/animals'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $uploadsDirectory: '%uploads_directory%'

    # Enregistrez explicitement les contrôleurs comme services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Service\ServiceManager:
        arguments:
            $uploadsDirectory: '%services_uploads_directory%'

    App\Service\HabitatService:
        arguments:
            $uploadsDirectory: '%habitats_uploads_directory%'

    App\Service\AnimalService:
        arguments:
            $uploadsDirectory: '%animals_uploads_directory%'

    App\EventListener\CompteRenduListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
