<?php

namespace ContainerT8focgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\AnimalService' shared autowired service.
     *
     * @return \App\Service\AnimalService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\AnimalService'])) {
            return $container->privates['App\\Service\\AnimalService'];
        }

        return $container->privates['App\\Service\\AnimalService'] = new \App\Service\AnimalService($a, (\dirname(__DIR__, 4).'/public/uploads/animals'), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')));
    }
}
