<?php

namespace ContainerT8focgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteRenduControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CompteRenduController' shared autowired service.
     *
     * @return \App\Controller\CompteRenduController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CompteRenduController'] = $instance = new \App\Controller\CompteRenduController();

        $instance->setContainer(($container->privates['.service_locator.nuHIcAe'] ?? $container->load('get_ServiceLocator_NuHIcAeService'))->withContext('App\\Controller\\CompteRenduController', $container));

        return $instance;
    }
}
