<?php

namespace ContainerT8focgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatControllernewService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ugfu8MF.App\Controller\HabitatController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ugfu8MF.App\\Controller\\HabitatController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitatService' => ['privates', 'App\\Service\\HabitatService', 'getHabitatServiceService', true],
        ], [
            'habitatService' => 'App\\Service\\HabitatService',
        ]))->withContext('App\\Controller\\HabitatController::new()', $container);
    }
}
