<?php

namespace ContainerT8focgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ofH3RGv.App\Controller\ServiceController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ofH3RGv'] ?? $container->load('get_ServiceLocator_OfH3RGvService'));

        if (isset($container->privates['.service_locator.ofH3RGv.App\\Controller\\ServiceController::edit()'])) {
            return $container->privates['.service_locator.ofH3RGv.App\\Controller\\ServiceController::edit()'];
        }

        return $container->privates['.service_locator.ofH3RGv.App\\Controller\\ServiceController::edit()'] = $a->withContext('App\\Controller\\ServiceController::edit()', $container);
    }
}
