<?php

namespace ContainerT8focgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestMailerCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\TestMailerCommand' shared autowired service.
     *
     * @return \App\Command\TestMailerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestMailerCommand'] = $instance = new \App\Command\TestMailerCommand(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));

        $instance->setName('app:test-mailer');

        return $instance;
    }
}
