<?php

namespace ContainerT8focgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.C3sIbBq.App\Controller\UserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C3sIbBq.App\\Controller\\UserController::delete()'] = ($container->privates['.service_locator.C3sIbBq'] ?? $container->load('get_ServiceLocator_C3sIbBqService'))->withContext('App\\Controller\\UserController::delete()', $container);
    }
}
