<?php

namespace ContainerI8LnEV9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteRenduService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KoDioFC.App\Entity\CompteRendu' shared service.
     *
     * @return \App\Entity\CompteRendu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KoDioFC": it needs an instance of "App\\Entity\\CompteRendu" but this type has been excluded in "config/services.yaml".');
    }
}
