<?php

namespace ContainerCjVYpyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteRenduRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CompteRenduRepository' shared autowired service.
     *
     * @return \App\Repository\CompteRenduRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CompteRenduRepository'] = new \App\Repository\CompteRenduRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
