<?php

namespace ContainerCjVYpyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ServiceManager' shared autowired service.
     *
     * @return \App\Service\ServiceManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ServiceManager'])) {
            return $container->privates['App\\Service\\ServiceManager'];
        }

        return $container->privates['App\\Service\\ServiceManager'] = new \App\Service\ServiceManager($a, (\dirname(__DIR__, 4).'/public/uploads/services'), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')));
    }
}
