<?php

namespace ContainerCjVYpyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\UserManager' shared autowired service.
     *
     * @return \App\Service\UserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\UserManager'])) {
            return $container->privates['App\\Service\\UserManager'];
        }

        return $container->privates['App\\Service\\UserManager'] = new \App\Service\UserManager($a, ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
