<?php

namespace ContainerDXuSxQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteRenduListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventListener\CompteRenduListener' shared autowired service.
     *
     * @return \App\EventListener\CompteRenduListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'CompteRenduListener.php';

        return $container->privates['App\\EventListener\\CompteRenduListener'] = new \App\EventListener\CompteRenduListener();
    }
}
