<?php

namespace ContainerDXuSxQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllerprofileService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.yC88959.App\Controller\PageController::profile()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yC88959.App\\Controller\\PageController::profile()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profileService' => ['privates', 'App\\Service\\ProfileService', 'getProfileServiceService', true],
        ], [
            'profileService' => 'App\\Service\\ProfileService',
        ]))->withContext('App\\Controller\\PageController::profile()', $container);
    }
}
