<?php

namespace ContainerDXuSxQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllernewService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ulT9bJa.App\Controller\ServiceController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ulT9bJa.App\\Controller\\ServiceController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceManager' => ['privates', 'App\\Service\\ServiceManager', 'getServiceManagerService', true],
        ], [
            'serviceManager' => 'App\\Service\\ServiceManager',
        ]))->withContext('App\\Controller\\ServiceController::new()', $container);
    }
}
