<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container46nloSh\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container46nloSh/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container46nloSh.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container46nloSh\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container46nloSh\App_KernelTestDebugContainer([
    'container.build_hash' => '46nloSh',
    'container.build_id' => '990c7ba6',
    'container.build_time' => 1733171226,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container46nloSh');
