<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI8LnEV9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI8LnEV9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI8LnEV9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI8LnEV9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI8LnEV9\App_KernelDevDebugContainer([
    'container.build_hash' => 'I8LnEV9',
    'container.build_id' => '6d4ce585',
    'container.build_time' => 1733493832,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI8LnEV9');
